{
 "title": "Memory Metrics Dashboard1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_demo_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Hog Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "app_memory_hog_allocated_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}